### ISSUE TITLE
Mark second word for drop caps if first only consists of one character

### ISSUE THREAD

**Issue by adunning** [tomduck/pandoc-lettrine#1]
I was absolutely delighted to find this filter. If the first word of a marked paragraph consists of only a single letter (e.g. 'O say'), normally one would put the second word in small caps. It would be great if the filter could handle this.

**Comment by tomduck** [comment]
My new project, [pandoc-latex-extensions](https://github.com/tomduck/pandoc-latex-extensions), handles this use case.  I plan to deprecate this project in favour of the new one.  Thanks for the suggestion.  Cheers, Tom.
