### ISSUE TITLE
Trigger filter with div/span

### ISSUE THREAD

**Issue by adunning** [tomduck/pandoc-lettrine#2]
One minor disadvantage of the current approach is that one ends up with stray brackets in exported documents other than LaTeX/HTML. This could be avoided by using a div and/or span instead (or providing this as an additional option).

**Comment by adunning** [comment]
Just noticed that Pandoc's LaTeX reader puts a span around the first letter of the paragraph with the class `lettrine` (e.g. `[T]{.lettrine}est`), so it would likely make most sense to support that.

**Comment by tomduck** [comment]
My new project, [pandoc-latex-extensions](https://github.com/tomduck/pandoc-latex-extensions), takes exactly the approach you have advocated.  Thanks for the suggestion.  I plan to deprecate this project in favour of the new one.  Cheers, Tom.
